### ISSUE TITLE
License.reg

### ISSUE THREAD

**Issue by James-1994** [brentyi/egoallo#4]
Hi,

I enjoyed your paper("Estimating Body and Hand Motion in an Ego‑sensed World"), and I’m interested in experimenting with your method for better understanding, but cannot due to lack of license. Would you be willing to add a license to your repo, such as MIT or Apache 2.0 or other license ?

Looking forward to your response.

Thanks !

**Comment by brentyi** [comment]
Hi, thanks for the note! I added an MIT license.
